### ISSUE TITLE
[8-9].item+p {color: red}  .item~p {color: yellow}  .item p {color: blue} p.item {color: blue} .item>p{color: blue} 分别是什么意思？

### ISSUE THREAD

**Issue by bigunclesuo** [bigunclesuo/jirengu#13]
```css
/* 是p元素，且class 为item的元素的下一相邻元素 */
.item+p {
  color: red;
}
/* 是p元素，且class 为item的元素的下N个相邻元素 */
.item~p {
  color: yellow;
}

/* class 为item的元素下面，所有p元素后代的颜色为蓝色 */
.item p {
  color: blue;
}

/* class为item的所有p元素颜色为蓝色 */
p.item {
  color: blue;
}

/* class 为item的元素下面，直接子元素为p元素的颜色为蓝色 */
.item>p {
  color: blue;
}
```
