### ISSUE TITLE
[8-9]em、rem分别是什么？

### ISSUE THREAD

**Issue by bigunclesuo** [bigunclesuo/jirengu#14]
## em
em 相对于body的font-size的倍数

## rem
rem 相对于html根节点默认样式16px的倍数

```css 
html {
    font-size: 62.5%; // 16px * 62.5 = 10px
}
body {
    font-size: 18px;
}
p {
     font-size: 2em; // 18px * 2
}
h1 {
     font-size: 2rem; // 10px * 2 
}
```
