### ISSUE TITLE
[8-9]CSS选择器常见的有几种?

### ISSUE THREAD

**Issue by bigunclesuo** [bigunclesuo/jirengu#17]
[mdn 选择器](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Introduction_to_CSS/Selectors)
## 简单选择器 Simple Selectors
1. 元素选择器 Element Selectors
```css
/* All p elements are red */
p {
  color: red;
}

/* All div elements are blue */
div {
  color: blue;
}
```
2. ID 选择器 ID Selectors
```css
#polite {
  font-family: cursive;
}

#rude {
  font-family: monospace;
  text-transform: uppercase;
}
```
3. 类选择器 Class Selectors
```css
/* The element with the class "first" is bolded */
.first {
  font-weight: bold;
}

/* All the elements with the class "done" are strike through */
.done {
  text-decoration: line-through;
}
```
4. 通用选择器 Universal Selector
```css
* {
  padding: 5px;
  border: 1px solid black;
  background: rgba(255,0,0,0.25)
}
```
