### ISSUE TITLE
[8-9]CSS 加载方式有几种

### ISSUE THREAD

**Issue by bigunclesuo** [bigunclesuo/jirengu#7]
## 外部样式表
1. 通过 <link> 引入 CSS。
```html
<link rel="stylesheet" href="style.css">
```
2. 通过 @import 引入样式，放入 css 中
```css
@import 'custom.css';
```

## 内部样式表
3. 将 CSS 放在页面的 <style>元素中
```css
<style>
    h1 { background: orange; }
</style>
```
4. 内联样式
```html
<p style="background: orange; font-size: 24px;">CSS is good</p>
 ```

5. 属性样式
```html
<img src="a.png" width=100 height=200 >
```
